### ISSUE TITLE
SPI speed

### ISSUE THREAD

**Issue by djamu** [pololu/amis-30543-arduino#1]
Thought that 500kHz for SPI was a bit slow.
tCLK specifies min 1us  > 1 Mhz which is imho still slow.

Tested with 3.3V interface.  ( teensy 3.2 )
Tested SPI upto 8Mhz, which works just fine. ( using it with 4Mhz ).
might be pullup / capacitance issues with 5V interface, or just wrong data on specs, will check with scope

**Comment by DavidEGrayson** [comment]
Thank you for letting us know that higher SPI frequencies worked for you.  Are you suggesting that we change the library to use a higher frequency?

**Comment by djamu** [comment]
I'll check the signal first with a 5V interface.
Is there a reason why you picked 500 kHz as a default speed for the SPI ?
For what platform ( which kind of arduino ) was this initially written ?

For me it was just too slow > transactions take 32us... which was far too long for my application, and writing nonblocking code a no go :-)

In any case, the default 500kHz should be good for any platform. No need to change code.
Anyone writing / using this code should check any issues anyway... 

Oh and thanks for the code, spec sheets are awfully poorly written in regards to SPI, seems you'd spent quite some time deciphering this one LOL...  :-)

**Comment by DavidEGrayson** [comment]
I picked 500 kHz because the maximum speed allowed by the AMIS-30543 datasheet is 1 MHz and I did not see a need to push that limit.  Why is 32 us too slow for you?

**Comment by djamu** [comment]
Spec sheet indicates a max step rate of 250khz ( min. 2 us for tNXT_HI hi + low ).
It wouldn't make sense to design a device that can't accept data between 2 step pulses. ( @ 250 khz steprate). Which is the initial reason why I tried pushing the SPI freq.

I'm finishing a high speed closed loop controller ( 25khz control loop ) driving solenoids on a ARM controller so I only have 40us  to do positioning / filtering & adjustments... power management ( of the amis-30543 chip)  is part of the control loop, since the driver is in a very small enclosure without cooling..... So I'm adjusting it hundreds times / sec to keep it cool.

**Comment by DavidEGrayson** [comment]
Thanks for the input.  I am closing this for now because I agree that we probably don't need to change the library code.
